env:
  node: true
  es2021: true
extends:
  - eslint:recommended
  # - plugin:@typescript-eslint/recommended
overrides: []
# parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: script
# plugins:
#   - '@typescript-eslint'
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  brace-style:
    - error
    - stroustrup

  # Temporarily turn off for gradual migration
  no-unused-vars:
    - off
  no-inner-declarations:
    - off
  no-prototype-builtins:
    - off
